import React from 'react';
import { clsx } from 'clsx';
import {
  Phone,
  Mail,
  Clock,
  MapPin,
  Search,
  ArrowRight,
  Play,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Youtube,
  HardHat,
  Hammer,
  Building2,
  TrendingUp,
  Users,
  Award,
  CheckCircle2,
  Quote,
  Star,
  Calendar,
  Menu,
  X,
  Home,
  Pencil,
  Clipboard,
  Settings,
  PaintBucket,
  TreeDeciduous,
  FileText,
  Files,
  FileCheck,
  Info,
  Plus,
  Minus,
  Zap,
  Briefcase,
  ShieldCheck,
  PenTool,
  DraftingCompass,
  Plug,
  Stamp,
  Landmark,
  Shovel,
  KeyRound,
  PiggyBank,
  ClipboardCheck,
  Lightbulb,
  Shield,
  Edit,
  Coins,
  HelpCircle,
  Wallet,
  Mountain,
  AlertTriangle,
  AlertCircle,
  XCircle,
  Map,
  Ruler,
  Layers,
  FileBadge,
  UserCheck,
  LayoutGrid,
  Fence,
  Umbrella,
  AreaChart,
  Leaf,
  Type,
  Check,
  Paperclip,
  Wind,
  MousePointer2,
  Link2,
  List,
  Filter,
  RefreshCw,
  SlidersHorizontal,
  ArrowUpDown,
  FlipHorizontal2,
  Pickaxe,
  Calculator,
  CalendarRange,
  Waves,
  Combine,
  Tractor,
  MessageCircle,
  Square,
  House,
  BrickWall,
  Box,
  Triangle,
  Pyramid,
  RectangleHorizontal,
  Columns3,
  Ban,
  Car,
  Flame,
  ThermometerSnowflake,
  FlameKindling,
  SquareDashedBottom,
  Handshake,
  ExternalLink,
  DoorClosed,
  ImageIcon,
  Droplets,
  CircleDot,
} from 'lucide-react';

const iconMap = {
  phone: Phone,
  mail: Mail,
  email: Mail,
  clock: Clock,
  mapPin: MapPin,
  location: MapPin,
  search: Search,
  arrowRight: ArrowRight,
  play: Play,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  youtube: Youtube,
  hardHat: HardHat,
  construction: HardHat,
  hammer: Hammer,
  building: Building2,
  trendingUp: TrendingUp,
  users: Users,
  award: Award,
  check: CheckCircle2,
  quote: Quote,
  star: Star,
  calendar: Calendar,
  menu: Menu,
  close: X,
  x: X,
  home: Home,
  pencil: Pencil,
  clipboard: Clipboard,
  settings: Settings,
  paintBrush: PaintBucket,
  tree: TreeDeciduous,
  fileText: FileText,
  files: Files,
  fileCheck: FileCheck,
  info: Info,
  plus: Plus,
  minus: Minus,
  zap: Zap,
  briefcase: Briefcase,
  shieldCheck: ShieldCheck,
  penTool: PenTool,
  draftingCompass: DraftingCompass,
  plug: Plug,
  stamp: Stamp,
  landmark: Landmark,
  shovel: Shovel,
  keyRound: KeyRound,
  piggyBank: PiggyBank,
  clipboardCheck: ClipboardCheck,
  lightbulb: Lightbulb,
  shield: Shield,
  edit: Edit,
  coins: Coins,
  helpCircle: HelpCircle,
  wallet: Wallet,
  mountain: Mountain,
  checkCircle: CheckCircle2,
  alertTriangle: AlertTriangle,
  alertCircle: AlertCircle,
  xCircle: XCircle,
  map: Map,
  ruler: Ruler,
  layers: Layers,
  fileBadge: FileBadge,
  userCheck: UserCheck,
  layoutGrid: LayoutGrid,
  gate: Fence,
  umbrella: Umbrella,
  areaChart: AreaChart,
  leaf: Leaf,
  leafIcon: Leaf,
  type: Type,
  checkmark: Check,
  paperclip: Paperclip,
  wind: Wind,
  mousePointer: MousePointer2,
  link: Link2,
  list: List,
  filter: Filter,
  refreshCw: RefreshCw,
  chevronUp: ChevronUp,
  slidersHorizontal: SlidersHorizontal,
  arrowUpDown: ArrowUpDown,
  flipHorizontal: FlipHorizontal2,
  pickaxe: Pickaxe,
  calculator: Calculator,
  calendarRange: CalendarRange,
  waves: Waves,
  combine: Combine,
  tractor: Tractor,
  messageCircle: MessageCircle,
  square: Square,
  house: House,
  brickWall: BrickWall,
  box: Box,
  triangle: Triangle,
  pyramid: Pyramid,
  rectangleHorizontal: RectangleHorizontal,
  columns3: Columns3,
  ban: Ban,
  car: Car,
  flame: Flame,
  thermometerSnowflake: ThermometerSnowflake,
  flameKindling: FlameKindling,
  squareDashedBottom: SquareDashedBottom,
  handshake: Handshake,
  externalLink: ExternalLink,
  doorClosed: DoorClosed,
  image: ImageIcon,
  droplets: Droplets,
  circleDot: CircleDot,
};

export type IconName = keyof typeof iconMap;

export interface IconProps {
  name: IconName;
  size?: 'sm' | 'md' | 'lg' | 'xl';
  className?: string;
}

export function Icon({ name, size = 'md', className }: IconProps) {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  const sizeClasses = {
    sm: 'w-4 h-4',
    md: 'w-5 h-5',
    lg: 'w-6 h-6',
    xl: 'w-8 h-8',
  };

  return (
    <IconComponent
      className={clsx(sizeClasses[size], className)}
      strokeWidth={2}
    />
  );
}


